id: P000595
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25652
  title: གཞོན་ནུའི་ཡིག་རྩལ་སྦྱོང་དེབ།
  author: ''
  volumes:
    37376fda86f94ed0b604df128a3c8ff1:
      image_group_id: I1KG25654
      title: ''
      volume_number: 1
      total_pages: 159
