id: P000595
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG25652
  title: གཞོན་ནུའི་ཡིག་རྩལ་སྦྱོང་དེབ།
  author: ''
  volumes:
    37376fda86f94ed0b604df128a3c8ff1:
      image_group_id: I1KG25654
      title: ''
      volume_number: 1
      total_pages: 159
